forge "http://forge.puppetlabs.com"

mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
  :tag => '4.3.2'

mod 'wget',
  :git => 'https://github.com/maestrodev/puppet-wget.git',
  :tag => 'v1.5.6'

mod 'nexus',
  :git => 'https://github.com/hubspotdevops/puppet-nexus.git',
  :tag => '1.3.1'

mod 'java',
  :git => 'https://github.com/puppetlabs/puppetlabs-java.git',
  :tag => '1.1.2'
