# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/centos-7.0-64-nocm"

  pe_version = '2015.2.0'
  config.pe_build.version       = pe_version
  config.pe_build.download_root = "https://s3.amazonaws.com/pe-builds/released/:version"

## Master
  config.vm.define :master do |master|

    master.vm.provider :vmware_fusion do |v|
      v.vmx["memsize"]  = "1024"
      v.vmx["numvcpus"] = "2"
    end

    master.vm.network :private_network, ip: "10.10.100.100"

    master.vm.hostname = 'master.puppetlabs.vm'
    master.vm.provision :hosts

    master.vm.provision :pe_bootstrap do |pe|
      pe.version = pe_version
      pe.role = :master
    end

    master.vm.provision "shell",
      inline: "service firewalld stop"
  end

## agent 1
  config.vm.define :agent1 do |agent|

    agent.vm.provider :vmware_fusion
    agent.vm.network :private_network, ip: "10.10.100.111"

    agent.vm.hostname = 'agent1.puppetlabs.vm'
    agent.vm.provision :hosts

    agent.vm.provision :pe_bootstrap do |pe|
      pe.version = pe_version
      pe.role = :agent
      pe.master = 'master.puppetlabs.vm'
    end
  end
end

